### ISSUE TITLE
Changer github action deploy / tag

### ISSUE THREAD

**Issue by vvatelot** [cnumr/EcoIndex#131]
# Afin de

Avoir un process de déploiement plus robuste et standardisé

# Je veux

Déployer le site uniquement sur un Tag

# Informations

- Le tag doit respecter le format semver et sera du style `vX.Y.Z`
- Modifier le trigger de la github action existante : 

```
on:
  push:
    tags:
      - 'v*.*.*'
```
